version: "3.9"
services:
  database:
    image: postgres
    container_name: ${DATABASE_CONTAINER_NAME}
    environment:
      # POSTGRES_DB: ${POSTGRES_DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  app:
    container_name:  ${APP_CONTAINER_NAME}
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        APP_DIR: ${APP_DIR}
        APP_USER: ${APP_USER}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - .:${APP_DIR}
    ports:
      - "3000:3000"
    depends_on:
      - database
