version: '2'

services:
  database:
    image: mdillon/postgis:9.5
    container_name: ${DATABASE_CONTAINER_NAME}
    environment:
      SERVICE: database
      POSTGRES_DB: ${POSTGRES_DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
     - "${POSTGRES_PORT}:5432"
    volumes:
      - /var/lib/postgresql/data

  redis:
    image: redis:3.0.5
    container_name: ${REDIS_CONTAINER_NAME}

  worker:
    container_name: ${WORKERS_CONTAINER_NAME}
    build:
      context: .
      dockerfile: Dockerfile.dev
    # command: bundle exec rake jobs:work
    volumes_from:
      - app
    links:
      - database
      - redis
    environment:
      SERVICE: worker
      ENV: ${ENV}
      APP_DIR: ${APP_DIR}
      PASSENGER_APP_ENV: ${ENV}
      POSTGRES_DB_NAME: ${POSTGRES_DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TERM: xterm-256color

  app:
    container_name: ${APP_CONTAINER_NAME}
    build:
      context: .
      dockerfile: Dockerfile.dev
    # command: /sbin/my_init -- bundle exec rails s -b 0.0.0.0 -p 3000
    ports:
     - "${APP_PORT}:3000"
     - "${SSH_PORT}:22" # ssh connections
    volumes:
     - .:${APP_DIR}
     - /usr/local/rvm/gems/ruby-2.2.5
     - ${APP_DIR}/vendor/assets/bower_components
    links:
      - database
      - redis
    environment:
      SERVICE: app
      ENV: ${ENV}
      APP_DIR: ${APP_DIR}
      PASSENGER_APP_ENV: ${ENV}
      POSTGRES_DB_NAME: ${POSTGRES_DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TERM: xterm-256color
